// Generated by AshTypescript - Shared Types
// Do not edit this file manually



export type AshDate = string;
export type UUID = string;
export type UtcDateTime = string;
export type UtcDateTimeUsec = string;

// Organization Schema
export type OrganizationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id";
  id: UUID;
};



export type OrganizationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id";
  id: UUID;
};


// User Schema
export type UserResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "organizationId" | "role" | "locale" | "jobTitle" | "birthday" | "startedAt";
  id: UUID;
  email: string;
  name: string;
  organizationId: UUID;
  role: "admin" | "manager" | "staff";
  locale: string;
  jobTitle: string;
  birthday: AshDate;
  startedAt: AshDate;
};



export type UserAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "email" | "name" | "organizationId" | "role" | "locale" | "jobTitle" | "birthday" | "startedAt";
  id: UUID;
  email: string;
  name: string;
  organizationId: UUID;
  role: "admin" | "manager" | "staff";
  locale: string;
  jobTitle: string;
  birthday: AshDate;
  startedAt: AshDate;
};


// Conversation Schema
export type ConversationResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "kind" | "title" | "venueId" | "shiftId";
  id: UUID;
  organizationId: UUID;
  kind: "shift_channel" | "venue_channel";
  title: string;
  venueId: UUID | null;
  shiftId: UUID | null;
};



export type ConversationAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "kind" | "title" | "venueId" | "shiftId";
  id: UUID;
  organizationId: UUID;
  kind: "shift_channel" | "venue_channel";
  title: string;
  venueId: UUID | null;
  shiftId: UUID | null;
};


// ConversationMembership Schema
export type ConversationMembershipResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "conversationId" | "userId" | "lastReadAt" | "unreadCount";
  id: UUID;
  conversationId: UUID;
  userId: UUID;
  lastReadAt: UtcDateTime | null;
  unreadCount: number;
  unreadSummary: { __type: "ComplexCalculation"; __returnType: {conversationId: UUID, lastReadAt: UtcDateTime | null, userId: UUID, __type: "TypedMap", __primitiveFields: "conversationId" | "lastReadAt" | "userId"} | null; };
};



export type ConversationMembershipAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "conversationId" | "userId" | "lastReadAt";
  id: UUID;
  conversationId: UUID;
  userId: UUID;
  lastReadAt: UtcDateTime | null;
};


// Message Schema
export type MessageResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "conversationId" | "authorId" | "body" | "insertedAt" | "updatedAt";
  id: UUID;
  organizationId: UUID;
  conversationId: UUID;
  authorId: UUID;
  body: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
  messageSummary: { __type: "ComplexCalculation"; __returnType: {authorId: UUID, body: string, conversationId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "authorId" | "body" | "conversationId" | "id" | "insertedAt"} | null; };
};



export type MessageAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "conversationId" | "authorId" | "body" | "insertedAt" | "updatedAt";
  id: UUID;
  organizationId: UUID;
  conversationId: UUID;
  authorId: UUID;
  body: string;
  insertedAt: UtcDateTimeUsec;
  updatedAt: UtcDateTimeUsec;
};


// Acknowledgement Schema
export type AcknowledgementResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "postId" | "userId";
  id: UUID;
  organizationId: UUID;
  postId: UUID;
  userId: UUID;
  ackSummary: { __type: "ComplexCalculation"; __returnType: {id: UUID, organizationId: UUID, postId: UUID, userId: UUID, __type: "TypedMap", __primitiveFields: "id" | "organizationId" | "postId" | "userId"} | null; };
};



export type AcknowledgementAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "postId" | "userId";
  id: UUID;
  organizationId: UUID;
  postId: UUID;
  userId: UUID;
};


// Post Schema
export type PostResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "venueId" | "authorId" | "title" | "body" | "originalLocale" | "requiresAcknowledgement" | "ackCount" | "acknowledgedByActor";
  id: UUID;
  organizationId: UUID;
  venueId: UUID | null;
  authorId: UUID;
  title: string;
  body: string;
  originalLocale: string;
  requiresAcknowledgement: boolean;
  ackCount: number;
  acknowledgedByActor: boolean | null;
  feedSummary: { __type: "ComplexCalculation"; __returnType: {authorId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, organizationId: UUID, title: string, venueId: UUID | null, __type: "TypedMap", __primitiveFields: "authorId" | "id" | "insertedAt" | "organizationId" | "title" | "venueId"} | null; };
};



export type PostAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "venueId" | "authorId" | "title" | "body" | "originalLocale" | "requiresAcknowledgement";
  id: UUID;
  organizationId: UUID;
  venueId: UUID | null;
  authorId: UUID;
  title: string;
  body: string;
  originalLocale: string;
  requiresAcknowledgement: boolean;
};


// Shoutout Schema
export type ShoutoutResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "senderId" | "recipientId" | "body";
  id: UUID;
  organizationId: UUID;
  senderId: UUID;
  recipientId: UUID;
  body: string;
  shoutoutSummary: { __type: "ComplexCalculation"; __returnType: {body: string, id: UUID, insertedAt: UtcDateTimeUsec, recipientId: UUID, senderId: UUID, __type: "TypedMap", __primitiveFields: "body" | "id" | "insertedAt" | "recipientId" | "senderId"} | null; };
};



export type ShoutoutAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "senderId" | "recipientId" | "body";
  id: UUID;
  organizationId: UUID;
  senderId: UUID;
  recipientId: UUID;
  body: string;
};


// Shift Schema
export type ShiftResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "startsAt" | "endsAt" | "organizationId" | "venueId";
  id: UUID;
  name: string;
  startsAt: UtcDateTime;
  endsAt: UtcDateTime;
  organizationId: UUID;
  venueId: UUID;
};



export type ShiftAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "startsAt" | "endsAt" | "organizationId" | "venueId";
  id: UUID;
  name: string;
  startsAt: UtcDateTime;
  endsAt: UtcDateTime;
  organizationId: UUID;
  venueId: UUID;
};


// ShiftAssignment Schema
export type ShiftAssignmentResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "shiftId" | "userId";
  id: UUID;
  organizationId: UUID;
  shiftId: UUID;
  userId: UUID;
};



export type ShiftAssignmentAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "shiftId" | "userId";
  id: UUID;
  organizationId: UUID;
  shiftId: UUID;
  userId: UUID;
};


// Venue Schema
export type VenueResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "city" | "timezone" | "organizationId";
  id: UUID;
  name: string;
  slug: string;
  city: string;
  timezone: string;
  organizationId: UUID;
  organization: { __type: "Relationship"; __resource: OrganizationResourceSchema; };
};



export type VenueAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "name" | "slug" | "city" | "timezone" | "organizationId";
  id: UUID;
  name: string;
  slug: string;
  city: string;
  timezone: string;
  organizationId: UUID;
};


// VenueMembership Schema
export type VenueMembershipResourceSchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "venueId" | "userId";
  id: UUID;
  organizationId: UUID;
  venueId: UUID;
  userId: UUID;
};



export type VenueMembershipAttributesOnlySchema = {
  __type: "Resource";
  __primitiveFields: "id" | "organizationId" | "venueId" | "userId";
  id: UUID;
  organizationId: UUID;
  venueId: UUID;
  userId: UUID;
};


export type OrganizationFilterInput = {
  and?: Array<OrganizationFilterInput>;
  or?: Array<OrganizationFilterInput>;
  not?: Array<OrganizationFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };



};
export type UserFilterInput = {
  and?: Array<UserFilterInput>;
  or?: Array<UserFilterInput>;
  not?: Array<UserFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  email?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  role?: {
    eq?: "admin" | "manager" | "staff";
    notEq?: "admin" | "manager" | "staff";
    in?: Array<"admin" | "manager" | "staff">;
  };

  locale?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  jobTitle?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  birthday?: {
    eq?: AshDate;
    notEq?: AshDate;
    greaterThan?: AshDate;
    greaterThanOrEqual?: AshDate;
    lessThan?: AshDate;
    lessThanOrEqual?: AshDate;
    in?: Array<AshDate>;
  };

  startedAt?: {
    eq?: AshDate;
    notEq?: AshDate;
    greaterThan?: AshDate;
    greaterThanOrEqual?: AshDate;
    lessThan?: AshDate;
    lessThanOrEqual?: AshDate;
    in?: Array<AshDate>;
  };



};
export type ConversationFilterInput = {
  and?: Array<ConversationFilterInput>;
  or?: Array<ConversationFilterInput>;
  not?: Array<ConversationFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  kind?: {
    eq?: "shift_channel" | "venue_channel";
    notEq?: "shift_channel" | "venue_channel";
    in?: Array<"shift_channel" | "venue_channel">;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  venueId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  shiftId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };



};
export type ConversationMembershipFilterInput = {
  and?: Array<ConversationMembershipFilterInput>;
  or?: Array<ConversationMembershipFilterInput>;
  not?: Array<ConversationMembershipFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  conversationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  lastReadAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
    isNil?: boolean;
  };

  unreadSummary?: {
    eq?: {conversationId: UUID, lastReadAt: UtcDateTime | null, userId: UUID, __type: "TypedMap", __primitiveFields: "conversationId" | "lastReadAt" | "userId"};
    notEq?: {conversationId: UUID, lastReadAt: UtcDateTime | null, userId: UUID, __type: "TypedMap", __primitiveFields: "conversationId" | "lastReadAt" | "userId"};
    in?: Array<{conversationId: UUID, lastReadAt: UtcDateTime | null, userId: UUID, __type: "TypedMap", __primitiveFields: "conversationId" | "lastReadAt" | "userId"}>;
    isNil?: boolean;
  };

  unreadCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };


};
export type MessageFilterInput = {
  and?: Array<MessageFilterInput>;
  or?: Array<MessageFilterInput>;
  not?: Array<MessageFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  conversationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  authorId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  insertedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  updatedAt?: {
    eq?: UtcDateTimeUsec;
    notEq?: UtcDateTimeUsec;
    greaterThan?: UtcDateTimeUsec;
    greaterThanOrEqual?: UtcDateTimeUsec;
    lessThan?: UtcDateTimeUsec;
    lessThanOrEqual?: UtcDateTimeUsec;
    in?: Array<UtcDateTimeUsec>;
  };

  messageSummary?: {
    eq?: {authorId: UUID, body: string, conversationId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "authorId" | "body" | "conversationId" | "id" | "insertedAt"};
    notEq?: {authorId: UUID, body: string, conversationId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "authorId" | "body" | "conversationId" | "id" | "insertedAt"};
    in?: Array<{authorId: UUID, body: string, conversationId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, __type: "TypedMap", __primitiveFields: "authorId" | "body" | "conversationId" | "id" | "insertedAt"}>;
    isNil?: boolean;
  };



};
export type AcknowledgementFilterInput = {
  and?: Array<AcknowledgementFilterInput>;
  or?: Array<AcknowledgementFilterInput>;
  not?: Array<AcknowledgementFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  postId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  ackSummary?: {
    eq?: {id: UUID, organizationId: UUID, postId: UUID, userId: UUID, __type: "TypedMap", __primitiveFields: "id" | "organizationId" | "postId" | "userId"};
    notEq?: {id: UUID, organizationId: UUID, postId: UUID, userId: UUID, __type: "TypedMap", __primitiveFields: "id" | "organizationId" | "postId" | "userId"};
    in?: Array<{id: UUID, organizationId: UUID, postId: UUID, userId: UUID, __type: "TypedMap", __primitiveFields: "id" | "organizationId" | "postId" | "userId"}>;
    isNil?: boolean;
  };



};
export type PostFilterInput = {
  and?: Array<PostFilterInput>;
  or?: Array<PostFilterInput>;
  not?: Array<PostFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  venueId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
    isNil?: boolean;
  };

  authorId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  title?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  originalLocale?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  requiresAcknowledgement?: {
    eq?: boolean;
    notEq?: boolean;
  };

  acknowledgedByActor?: {
    eq?: boolean;
    notEq?: boolean;
    isNil?: boolean;
  };

  feedSummary?: {
    eq?: {authorId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, organizationId: UUID, title: string, venueId: UUID | null, __type: "TypedMap", __primitiveFields: "authorId" | "id" | "insertedAt" | "organizationId" | "title" | "venueId"};
    notEq?: {authorId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, organizationId: UUID, title: string, venueId: UUID | null, __type: "TypedMap", __primitiveFields: "authorId" | "id" | "insertedAt" | "organizationId" | "title" | "venueId"};
    in?: Array<{authorId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, organizationId: UUID, title: string, venueId: UUID | null, __type: "TypedMap", __primitiveFields: "authorId" | "id" | "insertedAt" | "organizationId" | "title" | "venueId"}>;
    isNil?: boolean;
  };

  ackCount?: {
    eq?: number;
    notEq?: number;
    greaterThan?: number;
    greaterThanOrEqual?: number;
    lessThan?: number;
    lessThanOrEqual?: number;
    in?: Array<number>;
    isNil?: boolean;
  };


};
export type ShoutoutFilterInput = {
  and?: Array<ShoutoutFilterInput>;
  or?: Array<ShoutoutFilterInput>;
  not?: Array<ShoutoutFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  senderId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  recipientId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  body?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  shoutoutSummary?: {
    eq?: {body: string, id: UUID, insertedAt: UtcDateTimeUsec, recipientId: UUID, senderId: UUID, __type: "TypedMap", __primitiveFields: "body" | "id" | "insertedAt" | "recipientId" | "senderId"};
    notEq?: {body: string, id: UUID, insertedAt: UtcDateTimeUsec, recipientId: UUID, senderId: UUID, __type: "TypedMap", __primitiveFields: "body" | "id" | "insertedAt" | "recipientId" | "senderId"};
    in?: Array<{body: string, id: UUID, insertedAt: UtcDateTimeUsec, recipientId: UUID, senderId: UUID, __type: "TypedMap", __primitiveFields: "body" | "id" | "insertedAt" | "recipientId" | "senderId"}>;
    isNil?: boolean;
  };



};
export type ShiftFilterInput = {
  and?: Array<ShiftFilterInput>;
  or?: Array<ShiftFilterInput>;
  not?: Array<ShiftFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  startsAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
  };

  endsAt?: {
    eq?: UtcDateTime;
    notEq?: UtcDateTime;
    greaterThan?: UtcDateTime;
    greaterThanOrEqual?: UtcDateTime;
    lessThan?: UtcDateTime;
    lessThanOrEqual?: UtcDateTime;
    in?: Array<UtcDateTime>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  venueId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };



};
export type ShiftAssignmentFilterInput = {
  and?: Array<ShiftAssignmentFilterInput>;
  or?: Array<ShiftAssignmentFilterInput>;
  not?: Array<ShiftAssignmentFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  shiftId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };



};
export type VenueFilterInput = {
  and?: Array<VenueFilterInput>;
  or?: Array<VenueFilterInput>;
  not?: Array<VenueFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  name?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  slug?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  city?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  timezone?: {
    eq?: string;
    notEq?: string;
    in?: Array<string>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };


  organization?: OrganizationFilterInput;

};
export type VenueMembershipFilterInput = {
  and?: Array<VenueMembershipFilterInput>;
  or?: Array<VenueMembershipFilterInput>;
  not?: Array<VenueMembershipFilterInput>;

  id?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  organizationId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  venueId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };

  userId?: {
    eq?: UUID;
    notEq?: UUID;
    in?: Array<UUID>;
  };



};


export const organizationFilterFields = ["id"] as const;
export type OrganizationFilterField = (typeof organizationFilterFields)[number];

export const userFilterFields = ["id", "email", "name", "organizationId", "role", "locale", "jobTitle", "birthday", "startedAt"] as const;
export type UserFilterField = (typeof userFilterFields)[number];

export const conversationFilterFields = ["id", "organizationId", "kind", "title", "venueId", "shiftId"] as const;
export type ConversationFilterField = (typeof conversationFilterFields)[number];

export const conversationMembershipFilterFields = ["id", "conversationId", "userId", "lastReadAt", "unreadSummary", "unreadCount"] as const;
export type ConversationMembershipFilterField = (typeof conversationMembershipFilterFields)[number];

export const messageFilterFields = ["id", "organizationId", "conversationId", "authorId", "body", "insertedAt", "updatedAt", "messageSummary"] as const;
export type MessageFilterField = (typeof messageFilterFields)[number];

export const acknowledgementFilterFields = ["id", "organizationId", "postId", "userId", "ackSummary"] as const;
export type AcknowledgementFilterField = (typeof acknowledgementFilterFields)[number];

export const postFilterFields = ["id", "organizationId", "venueId", "authorId", "title", "body", "originalLocale", "requiresAcknowledgement", "acknowledgedByActor", "feedSummary", "ackCount"] as const;
export type PostFilterField = (typeof postFilterFields)[number];

export const shoutoutFilterFields = ["id", "organizationId", "senderId", "recipientId", "body", "shoutoutSummary"] as const;
export type ShoutoutFilterField = (typeof shoutoutFilterFields)[number];

export const shiftFilterFields = ["id", "name", "startsAt", "endsAt", "organizationId", "venueId"] as const;
export type ShiftFilterField = (typeof shiftFilterFields)[number];

export const shiftAssignmentFilterFields = ["id", "organizationId", "shiftId", "userId"] as const;
export type ShiftAssignmentFilterField = (typeof shiftAssignmentFilterFields)[number];

export const venueFilterFields = ["id", "name", "slug", "city", "timezone", "organizationId", "organization"] as const;
export type VenueFilterField = (typeof venueFilterFields)[number];

export const venueMembershipFilterFields = ["id", "organizationId", "venueId", "userId"] as const;
export type VenueMembershipFilterField = (typeof venueMembershipFilterFields)[number];


export const organizationSortFields = ["id"] as const;
export type OrganizationSortField = (typeof organizationSortFields)[number];

export const userSortFields = ["id", "email", "name", "organizationId", "role", "locale", "jobTitle", "birthday", "startedAt"] as const;
export type UserSortField = (typeof userSortFields)[number];

export const conversationSortFields = ["id", "organizationId", "kind", "title", "venueId", "shiftId"] as const;
export type ConversationSortField = (typeof conversationSortFields)[number];

export const conversationMembershipSortFields = ["id", "conversationId", "userId", "lastReadAt", "unreadSummary", "unreadCount"] as const;
export type ConversationMembershipSortField = (typeof conversationMembershipSortFields)[number];

export const messageSortFields = ["id", "organizationId", "conversationId", "authorId", "body", "insertedAt", "updatedAt", "messageSummary"] as const;
export type MessageSortField = (typeof messageSortFields)[number];

export const acknowledgementSortFields = ["id", "organizationId", "postId", "userId", "ackSummary"] as const;
export type AcknowledgementSortField = (typeof acknowledgementSortFields)[number];

export const postSortFields = ["id", "organizationId", "venueId", "authorId", "title", "body", "originalLocale", "requiresAcknowledgement", "acknowledgedByActor", "feedSummary", "ackCount"] as const;
export type PostSortField = (typeof postSortFields)[number];

export const shoutoutSortFields = ["id", "organizationId", "senderId", "recipientId", "body", "shoutoutSummary"] as const;
export type ShoutoutSortField = (typeof shoutoutSortFields)[number];

export const shiftSortFields = ["id", "name", "startsAt", "endsAt", "organizationId", "venueId"] as const;
export type ShiftSortField = (typeof shiftSortFields)[number];

export const shiftAssignmentSortFields = ["id", "organizationId", "shiftId", "userId"] as const;
export type ShiftAssignmentSortField = (typeof shiftAssignmentSortFields)[number];

export const venueSortFields = ["id", "name", "slug", "city", "timezone", "organizationId"] as const;
export type VenueSortField = (typeof venueSortFields)[number];

export const venueMembershipSortFields = ["id", "organizationId", "venueId", "userId"] as const;
export type VenueMembershipSortField = (typeof venueMembershipSortFields)[number];


// Utility Types

// Sort string type — allows optional direction prefix on sort field names
// Prefixes per Ash.Query.sort/3: + (asc), - (desc), ++ (asc_nils_first), -- (desc_nils_last)
export type SortString<T extends string> = T | `+${T}` | `-${T}` | `++${T}` | `--${T}`;

// Resource schema constraint
export type TypedSchema = {
  __type: "Resource" | "TypedMap" | "Union";
  __primitiveFields: string;
};

// Utility type to convert union to intersection
export type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;

// Helper type to infer union field values, avoiding duplication between array and non-array unions
export type InferUnionFieldValue<
  UnionSchema extends { __type: "Union"; __primitiveFields: any },
  FieldSelection extends any[],
> = UnionToIntersection<
  {
    [FieldIndex in keyof FieldSelection]: FieldSelection[FieldIndex] extends UnionSchema["__primitiveFields"]
      ? FieldSelection[FieldIndex] extends keyof UnionSchema
        ? { [P in FieldSelection[FieldIndex]]: UnionSchema[FieldSelection[FieldIndex]] }
        : never
      : FieldSelection[FieldIndex] extends Record<string, any>
        ? {
            [UnionKey in keyof FieldSelection[FieldIndex]]: UnionKey extends keyof UnionSchema
              ? NonNullable<UnionSchema[UnionKey]> extends { __array: true; __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                ? FieldSelection[FieldIndex][UnionKey] extends any[]
                  ? Array<
                      UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      >
                    > | null
                  : never
                : NonNullable<UnionSchema[UnionKey]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
                  ? FieldSelection[FieldIndex][UnionKey] extends any[]
                    ? UnionToIntersection<
                        {
                          [FieldIdx in keyof FieldSelection[FieldIndex][UnionKey]]: FieldSelection[FieldIndex][UnionKey][FieldIdx] extends TypedMapFields
                            ? FieldSelection[FieldIndex][UnionKey][FieldIdx] extends keyof NonNullable<UnionSchema[UnionKey]>
                              ? { [P in FieldSelection[FieldIndex][UnionKey][FieldIdx]]: NonNullable<UnionSchema[UnionKey]>[P] }
                              : never
                            : never;
                        }[number]
                      > | null
                    : never
                  : NonNullable<UnionSchema[UnionKey]> extends TypedSchema
                    ? InferResult<NonNullable<UnionSchema[UnionKey]>, FieldSelection[FieldIndex][UnionKey]>
                    : never
              : never;
          }
        : never;
  }[number]
>;

export type HasComplexFields<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
> extends never
  ? false
  : true;

export type ComplexFieldKeys<T extends TypedSchema> = keyof Omit<
  T,
  "__primitiveFields" | "__type" | T["__primitiveFields"]
>;

export type LeafFieldSelection<T extends TypedSchema> = T["__primitiveFields"];

export type ComplexFieldSelection<T extends TypedSchema> = {
  [K in ComplexFieldKeys<T>]?: T[K] extends {
    __type: "Relationship";
    __resource: infer Resource;
  }
    ? NonNullable<Resource> extends TypedSchema
      ? UnifiedFieldSelection<NonNullable<Resource>>[]
      : never
    : T[K] extends {
          __type: "ComplexCalculation";
          __returnType: infer ReturnType;
        }
      ? T[K] extends { __args: infer Args }
        ? NonNullable<ReturnType> extends TypedSchema
          ? {
              args: Args;
              fields: UnifiedFieldSelection<NonNullable<ReturnType>>[];
            }
          : { args: Args }
        : NonNullable<ReturnType> extends TypedSchema
          ? { fields: UnifiedFieldSelection<NonNullable<ReturnType>>[] }
          : never
      : T[K] extends { __type: "TypedMap" }
        ? NonNullable<T[K]> extends TypedSchema
          ? UnifiedFieldSelection<NonNullable<T[K]>>[]
          : never
        : T[K] extends { __type: "Union"; __primitiveFields: infer PrimitiveFields }
          ? T[K] extends { __array: true }
            ? (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields" | "__array">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : (PrimitiveFields | {
                [UnionKey in keyof Omit<T[K], "__type" | "__primitiveFields">]?: NonNullable<T[K][UnionKey]> extends { __type: "TypedMap"; __primitiveFields: any }
                  ? NonNullable<T[K][UnionKey]>["__primitiveFields"][]
                  : NonNullable<T[K][UnionKey]> extends TypedSchema
                    ? UnifiedFieldSelection<NonNullable<T[K][UnionKey]>>[]
                    : never;
              })[]
            : NonNullable<T[K]> extends TypedSchema
              ? UnifiedFieldSelection<NonNullable<T[K]>>[]
              : never;
};

// Main type: Use explicit base case detection to prevent infinite recursion
export type UnifiedFieldSelection<T extends TypedSchema> =
  HasComplexFields<T> extends false
    ? LeafFieldSelection<T> // Base case: only primitives, no recursion
    : LeafFieldSelection<T> | ComplexFieldSelection<T>; // Recursive case

export type InferFieldValue<
  T extends TypedSchema,
  Field,
> = Field extends T["__primitiveFields"]
  ? Field extends keyof T
    ? { [K in Field]: T[Field] }
    : never
  : Field extends Record<string, any>
    ? {
        [K in keyof Field]: K extends keyof T
          ? T[K] extends {
              __type: "Relationship";
              __resource: infer Resource;
            }
            ? NonNullable<Resource> extends TypedSchema
              ? T[K] extends { __array: true }
                ? Array<InferResult<NonNullable<Resource>, Field[K]>>
                : null extends Resource
                  ? InferResult<NonNullable<Resource>, Field[K]> | null
                  : InferResult<NonNullable<Resource>, Field[K]>
            : never
          : T[K] extends {
                __type: "ComplexCalculation";
                __returnType: infer ReturnType;
              }
            ? NonNullable<ReturnType> extends TypedSchema
              ? null extends ReturnType
                ? InferResult<NonNullable<ReturnType>, Field[K]["fields"]> | null
                : InferResult<NonNullable<ReturnType>, Field[K]["fields"]>
              : ReturnType
            : NonNullable<T[K]> extends { __type: "TypedMap"; __primitiveFields: infer TypedMapFields }
              ? NonNullable<T[K]> extends { __array: true }
                ? Field[K] extends any[]
                  ? null extends T[K]
                    ? Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      > | null
                    : Array<
                        UnionToIntersection<
                          {
                            [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                              ? E extends TypedMapFields
                                ? E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                                : E extends Record<string, any>
                                  ? {
                                      [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                        ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                          ? null extends NonNullable<T[K]>[NestedKey]
                                            ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                            : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                          : never
                                        : never;
                                    }
                                  : E extends keyof NonNullable<T[K]>
                                    ? { [P in E]: NonNullable<T[K]>[P] }
                                    : never
                              : never;
                          }[number]
                        >
                      >
                  : never
                : Field[K] extends any[]
                  ? null extends T[K]
                    ? UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof NonNullable<T[K]>
                                ? { [P in E]: NonNullable<T[K]>[P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      > | null
                    : UnionToIntersection<
                        {
                          [FieldIndex in keyof Field[K]]: Field[K][FieldIndex] extends infer E
                            ? E extends TypedMapFields
                              ? E extends keyof T[K]
                                ? { [P in E]: T[K][P] }
                                : never
                              : E extends Record<string, any>
                                ? {
                                    [NestedKey in keyof E]: NestedKey extends keyof NonNullable<T[K]>
                                      ? NonNullable<NonNullable<T[K]>[NestedKey]> extends TypedSchema
                                        ? null extends NonNullable<T[K]>[NestedKey]
                                          ? InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]> | null
                                          : InferResult<NonNullable<NonNullable<T[K]>[NestedKey]>, E[NestedKey]>
                                        : never
                                      : never;
                                  }
                                : E extends keyof NonNullable<T[K]>
                                  ? { [P in E]: NonNullable<T[K]>[P] }
                                  : never
                            : never;
                        }[number]
                      >
                  : never
              : T[K] extends { __type: "Union"; __primitiveFields: any }
                ? T[K] extends { __array: true }
                  ? Field[K] extends any[]
                    ? null extends T[K]
                      ? Array<InferUnionFieldValue<T[K], Field[K]>> | null
                      : Array<InferUnionFieldValue<T[K], Field[K]>>
                    : never
                  : Field[K] extends any[]
                    ? null extends T[K]
                      ? InferUnionFieldValue<T[K], Field[K]> | null
                      : InferUnionFieldValue<T[K], Field[K]>
                    : never
                  : NonNullable<T[K]> extends TypedSchema
                    ? null extends T[K]
                      ? InferResult<NonNullable<T[K]>, Field[K]> | null
                      : InferResult<NonNullable<T[K]>, Field[K]>
                    : never
          : never;
      }
    : never;

export type InferResult<
  T extends TypedSchema,
  SelectedFields extends UnifiedFieldSelection<T>[] | undefined,
> = SelectedFields extends undefined
  ? {}
  : SelectedFields extends []
  ? {}
  : SelectedFields extends UnifiedFieldSelection<T>[]
  ? UnionToIntersection<
      {
        [K in keyof SelectedFields]: InferFieldValue<T, SelectedFields[K]>;
      }[number]
    >
  : {};

// Pagination conditional types
// Checks if a page configuration object has any pagination parameters
export type HasPaginationParams<Page> =
  Page extends { offset: any } ? true :
  Page extends { after: any } ? true :
  Page extends { before: any } ? true :
  false;

// Infer which pagination type is being used from the page config
export type InferPaginationType<Page> =
  Page extends { offset: any } ? "offset" :
  Page extends { after: any } | { before: any } ? "keyset" :
  never;

// Returns either non-paginated (array) or paginated result based on page params
// For single pagination type support (offset-only or keyset-only)
// @ts-ignore
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export type ConditionalPaginatedResult<
  Page,
  RecordType,
  PaginatedType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? PaginatedType
    : RecordType;

// For actions supporting both offset and keyset pagination
// Infers the specific pagination type based on which params were passed
export type ConditionalPaginatedResultMixed<
  Page,
  RecordType,
  OffsetType,
  KeysetType
> = Page extends undefined
  ? RecordType
  : HasPaginationParams<Page> extends true
    ? InferPaginationType<Page> extends "offset"
      ? OffsetType
      : InferPaginationType<Page> extends "keyset"
        ? KeysetType
        : OffsetType | KeysetType  // Fallback to union if can't determine
    : RecordType;

export type SuccessDataFunc<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: true }
>["data"];


export type ErrorData<T extends (...args: any[]) => Promise<any>> = Extract<
  Awaited<ReturnType<T>>,
  { success: false }
>["errors"];

/**
 * Represents an error from an unsuccessful RPC call.
 *
 * This type matches the error structure defined in the AshTypescript.Rpc.Error protocol.
 *
 * @example
 * const error: AshRpcError = {
 *   type: "invalid_changes",
 *   message: "Invalid value for field %{field}",
 *   shortMessage: "Invalid changes",
 *   vars: { field: "email" },
 *   fields: ["email"],
 *   path: ["user", "email"],
 *   details: { suggestion: "Provide a valid email address" }
 * }
 */
export type AshRpcError = {
  /** Machine-readable error type (e.g., "invalid_changes", "not_found") */
  type: string;
  /** Full error message (may contain template variables like %{key}) */
  message: string;
  /** Concise version of the message */
  shortMessage: string;
  /** Variables to interpolate into the message template */
  vars: Record<string, any>;
  /** List of affected field names (for field-level errors) */
  fields: string[];
  /** Path to the error location in the data structure */
  path: string[];
  /** Optional map with extra details (e.g., suggestions, hints) */
  details?: Record<string, any>;
}

/**
 * Represents the result of a validation RPC call.
 *
 * All validation actions return this same structure, indicating either
 * successful validation or a list of validation errors.
 *
 * @example
 * // Successful validation
 * const result: ValidationResult = { success: true };
 *
 * // Failed validation
 * const result: ValidationResult = {
 *   success: false,
 *   errors: [
 *     {
 *       type: "required",
 *       message: "is required",
 *       shortMessage: "Required field",
 *       vars: { field: "email" },
 *       fields: ["email"],
 *       path: []
 *     }
 *   ]
 * };
 */
export type ValidationResult =
  | { success: true }
  | { success: false; errors: AshRpcError[]; };





export type AcknowledgementAddedPayload = {id: UUID, organizationId: UUID, postId: UUID, userId: UUID};
export type MessageCreatedPayload = {authorId: UUID, body: string, conversationId: UUID, id: UUID, insertedAt: UtcDateTimeUsec};
export type PostCreatedPayload = {authorId: UUID, id: UUID, insertedAt: UtcDateTimeUsec, organizationId: UUID, title: string, venueId: UUID | null};
export type ShoutoutCreatedPayload = {body: string, id: UUID, insertedAt: UtcDateTimeUsec, recipientId: UUID, senderId: UUID};
export type UnreadChangedPayload = {conversationId: UUID, lastReadAt: UtcDateTime | null, userId: UUID};

// Channel types for CrewPocWeb.ChatConversationChannel

export type ChatConversationChannel = {
  readonly __channelType: "ChatConversationChannel";
  on(event: string, callback: (payload: unknown) => void): number;
  off(event: string, ref: number): void;
};

export type ChatConversationChannelEvents = {
  message_created: MessageCreatedPayload;
};

export type ChatConversationChannelHandlers = {
  [E in keyof ChatConversationChannelEvents]?: (payload: ChatConversationChannelEvents[E]) => void;
};

export type ChatConversationChannelRefs = {
  [E in keyof ChatConversationChannelEvents]?: number;
};

// Channel types for CrewPocWeb.OrgFeedChannel

export type OrgFeedChannel = {
  readonly __channelType: "OrgFeedChannel";
  on(event: string, callback: (payload: unknown) => void): number;
  off(event: string, ref: number): void;
};

export type OrgFeedChannelEvents = {
  acknowledgement_added: AcknowledgementAddedPayload;
  post_created: PostCreatedPayload;
  shoutout_created: ShoutoutCreatedPayload;
};

export type OrgFeedChannelHandlers = {
  [E in keyof OrgFeedChannelEvents]?: (payload: OrgFeedChannelEvents[E]) => void;
};

export type OrgFeedChannelRefs = {
  [E in keyof OrgFeedChannelEvents]?: number;
};

// Channel types for CrewPocWeb.UserNotificationsChannel

export type UserNotificationsChannel = {
  readonly __channelType: "UserNotificationsChannel";
  on(event: string, callback: (payload: unknown) => void): number;
  off(event: string, ref: number): void;
};

export type UserNotificationsChannelEvents = {
  unread_changed: UnreadChangedPayload;
};

export type UserNotificationsChannelHandlers = {
  [E in keyof UserNotificationsChannelEvents]?: (payload: UserNotificationsChannelEvents[E]) => void;
};

export type UserNotificationsChannelRefs = {
  [E in keyof UserNotificationsChannelEvents]?: number;
};