// Generated by AshTypescript - RPC Actions
// Do not edit this file manually


import type { AshRpcError, ConditionalPaginatedResultMixed, ConversationFilterInput, ConversationMembershipFilterInput, ConversationMembershipResourceSchema, ConversationMembershipSortField, ConversationResourceSchema, ConversationSortField, InferResult, MessageFilterInput, MessageResourceSchema, MessageSortField, OrganizationFilterInput, OrganizationResourceSchema, OrganizationSortField, ShiftAssignmentFilterInput, ShiftAssignmentResourceSchema, ShiftAssignmentSortField, ShiftFilterInput, ShiftResourceSchema, ShiftSortField, SortString, UUID, UnifiedFieldSelection, UserFilterInput, UserResourceSchema, UserSortField, ValidationResult, VenueFilterInput, VenueMembershipFilterInput, VenueMembershipResourceSchema, VenueMembershipSortField, VenueResourceSchema, VenueSortField } from "./ash_types";
export type * from "./ash_types";

// Helper Functions

/**
 * Configuration options for action RPC requests
 */
export interface ActionConfig {
  // Request data
  input?: Record<string, any>;
  identity?: any;
  fields?: Array<string | Record<string, any>>; // Field selection
  filter?: Record<string, any>; // Filter options (for reads)
  sort?: string | string[]; // Sort options
  page?:
    | {
        // Offset-based pagination
        limit?: number;
        offset?: number;
        count?: boolean;
      }
    | {
        // Keyset pagination
        limit?: number;
        after?: string;
        before?: string;
      };

  // Metadata
  metadataFields?: ReadonlyArray<string>;

  // HTTP customization
  headers?: Record<string, string>; // Custom headers
  fetchOptions?: RequestInit; // Fetch options (signal, cache, etc.)
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Multitenancy
  tenant?: string; // Tenant parameter

  // Hook context
  hookCtx?: Record<string, any>;
}

/**
 * Configuration options for validation RPC requests
 */
export interface ValidationConfig {
  // Request data
  input?: Record<string, any>;

  // HTTP customization
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;

  // Hook context
  hookCtx?: Record<string, any>;
}




/**
 * Gets the CSRF token from the page's meta tag
 * Returns null if no CSRF token is found
 */
export function getPhoenixCSRFToken(): string | null {
  return document
    ?.querySelector("meta[name='csrf-token']")
    ?.getAttribute("content") || null;
}

/**
 * Builds headers object with CSRF token for Phoenix applications
 * Returns headers object with X-CSRF-Token (if available)
 */
export function buildCSRFHeaders(headers: Record<string, string> = {}): Record<string, string> {
  const csrfToken = getPhoenixCSRFToken();
  if (csrfToken) {
    headers["X-CSRF-Token"] = csrfToken;
  }

  return headers;
}

/**
 * Internal helper function for making action RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ActionConfig
 */
export async function executeActionRpcRequest<T>(
  payload: Record<string, any>,
  config: ActionConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/run", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}


/**
 * Internal helper function for making validation RPC requests
 * Handles hooks, request configuration, fetch execution, and error handling
 * @param config Configuration matching ValidationConfig
 */
export async function executeValidationRpcRequest<T>(
  payload: Record<string, any>,
  config: ValidationConfig
): Promise<T> {
    const processedConfig = config;

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
    ...config.headers,
  };

  const fetchFunction = config.customFetch || processedConfig.customFetch || fetch;
  const fetchOptions: RequestInit = {
    ...processedConfig.fetchOptions,
    ...config.fetchOptions,
    method: "POST",
    headers,
    body: JSON.stringify(payload),
  };

  const response = await fetchFunction("/rpc/validate", fetchOptions);
  const result = response.ok ? await response.json() : null;


  if (!response.ok) {
    return {
      success: false,
      errors: [
        {
          type: "network_error",
          message: `Network request failed: ${response.statusText}`,
          shortMessage: "Network error",
          vars: { statusCode: response.status, statusText: response.statusText },
          fields: [],
          path: [],
          details: { statusCode: response.status }
        }
      ],
    } as T;
  }

  return result as T;
}







export type GetOrganizationFields = UnifiedFieldSelection<OrganizationResourceSchema>[];


export type InferGetOrganizationResult<
  Fields extends GetOrganizationFields | undefined,
  Page extends GetOrganizationConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<OrganizationResourceSchema, Fields>>, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<OrganizationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetOrganizationConfig = {
  tenant?: string;
  fields: GetOrganizationFields;
  filter?: OrganizationFilterInput;
  sort?: SortString<OrganizationSortField> | SortString<OrganizationSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetOrganizationResult<Fields extends GetOrganizationFields, Page extends GetOrganizationConfig["page"] = undefined> = | { success: true; data: InferGetOrganizationResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Organization records
 *
 * @ashActionType :read
 */
export async function getOrganization<Fields extends GetOrganizationFields, Config extends GetOrganizationConfig = GetOrganizationConfig>(
  config: Config & { fields: Fields }
): Promise<GetOrganizationResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_organization",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetOrganizationResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Organization records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetOrganization(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_organization",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type CelebratingTodayFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferCelebratingTodayResult<
  Fields extends CelebratingTodayFields,
> = Array<InferResult<UserResourceSchema, Fields>>;

export type CelebratingTodayResult<Fields extends CelebratingTodayFields> = | { success: true; data: InferCelebratingTodayResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function celebratingToday<Fields extends CelebratingTodayFields>(
  config: {
  tenant?: string;
  fields: Fields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<CelebratingTodayResult<Fields>> {
  const payload = {
    action: "celebrating_today",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort })
  };

  return executeActionRpcRequest<CelebratingTodayResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateCelebratingToday(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "celebrating_today",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetCurrentUserFields = UnifiedFieldSelection<UserResourceSchema>[];
export type InferGetCurrentUserResult<
  Fields extends GetCurrentUserFields,
> = InferResult<UserResourceSchema, Fields>;

export type GetCurrentUserResult<Fields extends GetCurrentUserFields> = | { success: true; data: InferGetCurrentUserResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getCurrentUser<Fields extends GetCurrentUserFields>(
  config: {
  tenant?: string;
  fields: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<GetCurrentUserResult<Fields>> {
  const payload = {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<GetCurrentUserResult<Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetCurrentUser(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_current_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type GetUserFields = UnifiedFieldSelection<UserResourceSchema>[];


export type InferGetUserResult<
  Fields extends GetUserFields | undefined,
  Page extends GetUserConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<UserResourceSchema, Fields>>, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type GetUserConfig = {
  tenant?: string;
  fields: GetUserFields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type GetUserResult<Fields extends GetUserFields, Page extends GetUserConfig["page"] = undefined> = | { success: true; data: InferGetUserResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function getUser<Fields extends GetUserFields, Config extends GetUserConfig = GetUserConfig>(
  config: Config & { fields: Fields }
): Promise<GetUserResult<Fields, Config["page"]>> {
  const payload = {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<GetUserResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateGetUser(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "get_user",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListUsersFields = UnifiedFieldSelection<UserResourceSchema>[];


export type InferListUsersResult<
  Fields extends ListUsersFields | undefined,
  Page extends ListUsersConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<UserResourceSchema, Fields>>, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<UserResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListUsersConfig = {
  tenant?: string;
  fields: ListUsersFields;
  filter?: UserFilterInput;
  sort?: SortString<UserSortField> | SortString<UserSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListUsersResult<Fields extends ListUsersFields, Page extends ListUsersConfig["page"] = undefined> = | { success: true; data: InferListUsersResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read User records
 *
 * @ashActionType :read
 */
export async function listUsers<Fields extends ListUsersFields, Config extends ListUsersConfig = ListUsersConfig>(
  config: Config & { fields: Fields }
): Promise<ListUsersResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListUsersResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read User records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListUsers(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_users",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListConversationsFields = UnifiedFieldSelection<ConversationResourceSchema>[];


export type InferListConversationsResult<
  Fields extends ListConversationsFields | undefined,
  Page extends ListConversationsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ConversationResourceSchema, Fields>>, {
  results: Array<InferResult<ConversationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ConversationResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListConversationsConfig = {
  tenant?: string;
  fields: ListConversationsFields;
  filter?: ConversationFilterInput;
  sort?: SortString<ConversationSortField> | SortString<ConversationSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListConversationsResult<Fields extends ListConversationsFields, Page extends ListConversationsConfig["page"] = undefined> = | { success: true; data: InferListConversationsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Conversation records
 *
 * @ashActionType :read
 */
export async function listConversations<Fields extends ListConversationsFields, Config extends ListConversationsConfig = ListConversationsConfig>(
  config: Config & { fields: Fields }
): Promise<ListConversationsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_conversations",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListConversationsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Conversation records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListConversations(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_conversations",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListConversationMembershipsFields = UnifiedFieldSelection<ConversationMembershipResourceSchema>[];


export type InferListConversationMembershipsResult<
  Fields extends ListConversationMembershipsFields | undefined,
  Page extends ListConversationMembershipsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ConversationMembershipResourceSchema, Fields>>, {
  results: Array<InferResult<ConversationMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ConversationMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListConversationMembershipsConfig = {
  tenant?: string;
  fields: ListConversationMembershipsFields;
  filter?: ConversationMembershipFilterInput;
  sort?: SortString<ConversationMembershipSortField> | SortString<ConversationMembershipSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListConversationMembershipsResult<Fields extends ListConversationMembershipsFields, Page extends ListConversationMembershipsConfig["page"] = undefined> = | { success: true; data: InferListConversationMembershipsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ConversationMembership records
 *
 * @ashActionType :read
 */
export async function listConversationMemberships<Fields extends ListConversationMembershipsFields, Config extends ListConversationMembershipsConfig = ListConversationMembershipsConfig>(
  config: Config & { fields: Fields }
): Promise<ListConversationMembershipsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_conversation_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListConversationMembershipsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read ConversationMembership records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListConversationMemberships(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_conversation_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type MarkConversationReadFields = UnifiedFieldSelection<ConversationMembershipResourceSchema>[];

export type InferMarkConversationReadResult<
  Fields extends MarkConversationReadFields | undefined,
> = InferResult<ConversationMembershipResourceSchema, Fields>;

export type MarkConversationReadResult<Fields extends MarkConversationReadFields | undefined = undefined> = | { success: true; data: InferMarkConversationReadResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Update an existing ConversationMembership
 *
 * @ashActionType :update
 */
export async function markConversationRead<Fields extends MarkConversationReadFields | undefined = undefined>(
  config: {
  tenant?: string;
  identity: UUID;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<MarkConversationReadResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "mark_conversation_read",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<MarkConversationReadResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Update an existing ConversationMembership
 *
 * @ashActionType :update
 * @validation true
 */
export async function validateMarkConversationRead(
  config: {
  tenant?: string;
  identity: UUID | string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "mark_conversation_read",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    identity: config.identity
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListMessagesFields = UnifiedFieldSelection<MessageResourceSchema>[];


export type InferListMessagesResult<
  Fields extends ListMessagesFields | undefined,
  Page extends ListMessagesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<MessageResourceSchema, Fields>>, {
  results: Array<InferResult<MessageResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<MessageResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListMessagesConfig = {
  tenant?: string;
  fields: ListMessagesFields;
  filter?: MessageFilterInput;
  sort?: SortString<MessageSortField> | SortString<MessageSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListMessagesResult<Fields extends ListMessagesFields, Page extends ListMessagesConfig["page"] = undefined> = | { success: true; data: InferListMessagesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Message records
 *
 * @ashActionType :read
 */
export async function listMessages<Fields extends ListMessagesFields, Config extends ListMessagesConfig = ListMessagesConfig>(
  config: Config & { fields: Fields }
): Promise<ListMessagesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_messages",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListMessagesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Message records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListMessages(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_messages",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type SendMessageInput = {
  conversationId: UUID;
  body: string;
};

export type SendMessageFields = UnifiedFieldSelection<MessageResourceSchema>[];

export type InferSendMessageResult<
  Fields extends SendMessageFields | undefined,
> = InferResult<MessageResourceSchema, Fields>;

export type SendMessageResult<Fields extends SendMessageFields | undefined = undefined> = | { success: true; data: InferSendMessageResult<Fields>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Create a new Message
 *
 * @ashActionType :create
 */
export async function sendMessage<Fields extends SendMessageFields | undefined = undefined>(
  config: {
  tenant?: string;
  input: SendMessageInput;
  fields?: Fields;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<SendMessageResult<Fields extends undefined ? [] : Fields>> {
  const payload = {
    action: "send_message",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input,
    ...(config.fields !== undefined && { fields: config.fields })
  };

  return executeActionRpcRequest<SendMessageResult<Fields extends undefined ? [] : Fields>>(
    payload,
    config
  );
}


/**
 * Validate: Create a new Message
 *
 * @ashActionType :create
 * @validation true
 */
export async function validateSendMessage(
  config: {
  tenant?: string;
  input: SendMessageInput;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "send_message",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    input: config.input
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListShiftsFields = UnifiedFieldSelection<ShiftResourceSchema>[];


export type InferListShiftsResult<
  Fields extends ListShiftsFields | undefined,
  Page extends ListShiftsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ShiftResourceSchema, Fields>>, {
  results: Array<InferResult<ShiftResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ShiftResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListShiftsConfig = {
  tenant?: string;
  fields: ListShiftsFields;
  filter?: ShiftFilterInput;
  sort?: SortString<ShiftSortField> | SortString<ShiftSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListShiftsResult<Fields extends ListShiftsFields, Page extends ListShiftsConfig["page"] = undefined> = | { success: true; data: InferListShiftsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Shift records
 *
 * @ashActionType :read
 */
export async function listShifts<Fields extends ListShiftsFields, Config extends ListShiftsConfig = ListShiftsConfig>(
  config: Config & { fields: Fields }
): Promise<ListShiftsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_shifts",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListShiftsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Shift records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListShifts(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_shifts",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListShiftAssignmentsFields = UnifiedFieldSelection<ShiftAssignmentResourceSchema>[];


export type InferListShiftAssignmentsResult<
  Fields extends ListShiftAssignmentsFields | undefined,
  Page extends ListShiftAssignmentsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<ShiftAssignmentResourceSchema, Fields>>, {
  results: Array<InferResult<ShiftAssignmentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<ShiftAssignmentResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListShiftAssignmentsConfig = {
  tenant?: string;
  fields: ListShiftAssignmentsFields;
  filter?: ShiftAssignmentFilterInput;
  sort?: SortString<ShiftAssignmentSortField> | SortString<ShiftAssignmentSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListShiftAssignmentsResult<Fields extends ListShiftAssignmentsFields, Page extends ListShiftAssignmentsConfig["page"] = undefined> = | { success: true; data: InferListShiftAssignmentsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read ShiftAssignment records
 *
 * @ashActionType :read
 */
export async function listShiftAssignments<Fields extends ListShiftAssignmentsFields, Config extends ListShiftAssignmentsConfig = ListShiftAssignmentsConfig>(
  config: Config & { fields: Fields }
): Promise<ListShiftAssignmentsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_shift_assignments",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListShiftAssignmentsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read ShiftAssignment records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListShiftAssignments(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_shift_assignments",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListVenuesFields = UnifiedFieldSelection<VenueResourceSchema>[];


export type InferListVenuesResult<
  Fields extends ListVenuesFields | undefined,
  Page extends ListVenuesConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<VenueResourceSchema, Fields>>, {
  results: Array<InferResult<VenueResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<VenueResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListVenuesConfig = {
  tenant?: string;
  fields: ListVenuesFields;
  filter?: VenueFilterInput;
  sort?: SortString<VenueSortField> | SortString<VenueSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListVenuesResult<Fields extends ListVenuesFields, Page extends ListVenuesConfig["page"] = undefined> = | { success: true; data: InferListVenuesResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read Venue records
 *
 * @ashActionType :read
 */
export async function listVenues<Fields extends ListVenuesFields, Config extends ListVenuesConfig = ListVenuesConfig>(
  config: Config & { fields: Fields }
): Promise<ListVenuesResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_venues",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListVenuesResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read Venue records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListVenues(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_venues",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}


export type ListVenueMembershipsFields = UnifiedFieldSelection<VenueMembershipResourceSchema>[];


export type InferListVenueMembershipsResult<
  Fields extends ListVenueMembershipsFields | undefined,
  Page extends ListVenueMembershipsConfig["page"] = undefined
> = ConditionalPaginatedResultMixed<Page, Array<InferResult<VenueMembershipResourceSchema, Fields>>, {
  results: Array<InferResult<VenueMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  offset: number;
  count?: number | null;
  type: "offset";
}, {
  results: Array<InferResult<VenueMembershipResourceSchema, Fields>>;
  hasMore: boolean;
  limit: number;
  after: string | null;
  before: string | null;
  previousPage: string;
  nextPage: string;
  count?: number | null;
  type: "keyset";
}>;

export type ListVenueMembershipsConfig = {
  tenant?: string;
  fields: ListVenueMembershipsFields;
  filter?: VenueMembershipFilterInput;
  sort?: SortString<VenueMembershipSortField> | SortString<VenueMembershipSortField>[];
  page?: (
    {
      limit?: number;
      offset?: number;
      count?: boolean;
    } | {
      limit?: number;
      after?: string;
      before?: string;
    }
  );
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
};

export type ListVenueMembershipsResult<Fields extends ListVenueMembershipsFields, Page extends ListVenueMembershipsConfig["page"] = undefined> = | { success: true; data: InferListVenueMembershipsResult<Fields, Page>; }
| { success: false; errors: AshRpcError[]; }

;

/**
 * Read VenueMembership records
 *
 * @ashActionType :read
 */
export async function listVenueMemberships<Fields extends ListVenueMembershipsFields, Config extends ListVenueMembershipsConfig = ListVenueMembershipsConfig>(
  config: Config & { fields: Fields }
): Promise<ListVenueMembershipsResult<Fields, Config["page"]>> {
  const payload = {
    action: "list_venue_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant }),
    ...(config.fields !== undefined && { fields: config.fields }),
    ...(config.filter && { filter: config.filter }),
    ...(config.sort && { sort: Array.isArray(config.sort) ? config.sort.join(",") : config.sort }),
    ...(config.page && { page: config.page })
  };

  return executeActionRpcRequest<ListVenueMembershipsResult<Fields, Config["page"]>>(
    payload,
    config
  );
}


/**
 * Validate: Read VenueMembership records
 *
 * @ashActionType :read
 * @validation true
 */
export async function validateListVenueMemberships(
  config: {
  tenant?: string;
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
}
): Promise<ValidationResult> {
  const payload = {
    action: "list_venue_memberships",
    ...(config.tenant !== undefined && { tenant: config.tenant })
  };

  return executeValidationRpcRequest<ValidationResult>(
    payload,
    config
  );
}

