// This file is auto-generated by AshTypescript. Do not edit manually.


export type * from "./ash_types";
/**
 * Configuration options for typed controller requests
 */
export interface TypedControllerConfig {
  headers?: Record<string, string>;
  fetchOptions?: RequestInit;
  customFetch?: (
    input: RequestInfo | URL,
    init?: RequestInit,
  ) => Promise<Response>;
}

/**
 * Internal helper function for making typed controller requests
 */
export async function executeTypedControllerRequest(
  url: string,
  method: string,
  _actionName: string,
  body: string | undefined,
  config?: TypedControllerConfig,
): Promise<Response> {
    const processedConfig = config || {};

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    ...processedConfig.headers,
  };

  const fetchFunction = processedConfig.customFetch || fetch;
  const fetchInit: RequestInit = {
    ...processedConfig.fetchOptions,
    method,
    headers,
    ...(body !== undefined ? { body } : {}),
  };

  const response = await fetchFunction(url, fetchInit);


  return response;
}

/**
 * Path helper for /api/switch_user
 */
export function switchUserPath(): string {
  return "/api/switch_user";
}

export type SwitchUserInput = {
  userId: string;
};
/**
 * POST /api/switch_user
 */
export async function switchUser(input: SwitchUserInput, config?: TypedControllerConfig): Promise<Response> {
  return executeTypedControllerRequest("/api/switch_user", "POST", "switchUser", JSON.stringify(input), config);
}
