defmodule CrewPoc.Repo.Migrations.AddShiftsDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shifts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :starts_at, :utc_datetime, null: false
      add :ends_at, :utc_datetime, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "shifts_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :venue_id,
          references(:venues,
            column: :id,
            name: "shifts_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:shift_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "shift_assignments_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :shift_id,
          references(:shifts,
            column: :id,
            name: "shift_assignments_shift_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "shift_assignments_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:shift_assignments, [:user_id, :shift_id],
             name: "shift_assignments_unique_user_shift_index"
           )

    create constraint(:shifts, :ends_after_starts,
             check: """
               ends_at > starts_at
             """
           )
  end

  def down do
    drop_if_exists constraint(:shifts, :ends_after_starts)

    drop constraint(:shift_assignments, "shift_assignments_organization_id_fkey")

    drop constraint(:shift_assignments, "shift_assignments_shift_id_fkey")

    drop constraint(:shift_assignments, "shift_assignments_user_id_fkey")

    drop_if_exists unique_index(:shift_assignments, [:user_id, :shift_id],
                     name: "shift_assignments_unique_user_shift_index"
                   )

    drop table(:shift_assignments)

    drop constraint(:shifts, "shifts_organization_id_fkey")

    drop constraint(:shifts, "shifts_venue_id_fkey")

    drop table(:shifts)
  end
end
