defmodule CrewPoc.Repo.Migrations.DropConversationMembershipOrganizationId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversation_memberships) do
      remove :organization_id
    end
  end

  def down do
    alter table(:conversation_memberships) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "conversation_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end
end
