defmodule CrewPoc.Repo.Migrations.AddChatDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:messages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "messages_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id, :uuid, null: false
      add :author_id, :uuid, null: false
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:conversations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :author_id,
             references(:users,
               column: :id,
               name: "messages_author_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:conversations) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "conversations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :kind, :text, null: false
      add :title, :text, null: false

      add :venue_id,
          references(:venues,
            column: :id,
            name: "conversations_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :shift_id,
          references(:shifts,
            column: :id,
            name: "conversations_shift_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:conversations, [:shift_id],
             name: "conversations_unique_shift_channel_index",
             unique: true,
             where: "kind = 'shift_channel'"
           )

    create index(:conversations, [:venue_id],
             name: "conversations_unique_venue_channel_index",
             unique: true,
             where: "kind = 'venue_channel'"
           )

    create table(:conversation_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "conversation_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "conversation_memberships_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "conversation_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :last_read_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:conversation_memberships, [:conversation_id, :user_id],
             name: "conversation_memberships_unique_user_conversation_index"
           )
  end

  def down do
    drop constraint(:conversation_memberships, "conversation_memberships_organization_id_fkey")

    drop constraint(:conversation_memberships, "conversation_memberships_conversation_id_fkey")

    drop constraint(:conversation_memberships, "conversation_memberships_user_id_fkey")

    drop_if_exists unique_index(:conversation_memberships, [:conversation_id, :user_id],
                     name: "conversation_memberships_unique_user_conversation_index"
                   )

    drop table(:conversation_memberships)

    drop constraint(:conversations, "conversations_organization_id_fkey")

    drop constraint(:conversations, "conversations_venue_id_fkey")

    drop constraint(:conversations, "conversations_shift_id_fkey")

    drop_if_exists index(:conversations, [:venue_id],
                     name: "conversations_unique_venue_channel_index"
                   )

    drop_if_exists index(:conversations, [:shift_id],
                     name: "conversations_unique_shift_channel_index"
                   )

    alter table(:conversations) do
      remove :updated_at
      remove :inserted_at
      remove :shift_id
      remove :venue_id
      remove :title
      remove :kind
      remove :organization_id
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_author_id_fkey")

    alter table(:messages) do
      modify :author_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop constraint(:messages, "messages_organization_id_fkey")

    drop table(:messages)
  end
end
