defmodule CrewPoc.Repo.Migrations.AddChatCascades do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:conversations, "conversations_shift_id_fkey")

    drop constraint(:conversations, "conversations_venue_id_fkey")

    alter table(:conversations) do
      modify :venue_id,
             references(:venues,
               column: :id,
               name: "conversations_venue_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :shift_id,
             references(:shifts,
               column: :id,
               name: "conversations_shift_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:conversation_memberships, "conversation_memberships_conversation_id_fkey")

    alter table(:conversation_memberships) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_memberships_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:conversation_memberships, "conversation_memberships_conversation_id_fkey")

    alter table(:conversation_memberships) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "conversation_memberships_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:conversations, "conversations_venue_id_fkey")

    drop constraint(:conversations, "conversations_shift_id_fkey")

    alter table(:conversations) do
      modify :shift_id,
             references(:shifts,
               column: :id,
               name: "conversations_shift_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:venues,
               column: :id,
               name: "conversations_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    alter table(:messages) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "messages_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
