defmodule CrewPoc.Repo.Migrations.AddFeedAndRecognitionDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shoutouts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "shoutouts_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :sender_id,
          references(:users,
            column: :id,
            name: "shoutouts_sender_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :recipient_id,
          references(:users,
            column: :id,
            name: "shoutouts_recipient_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:shoutouts, ["body gin_trgm_ops"],
             name: "shoutouts_body_gin_index",
             using: "GIN"
           )

    create table(:posts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "posts_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :venue_id,
          references(:venues,
            column: :id,
            name: "posts_venue_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      add :author_id,
          references(:users,
            column: :id,
            name: "posts_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :title, :text, null: false
      add :body, :text, null: false
      add :original_locale, :text, null: false, default: "en"
      add :requires_acknowledgement, :boolean, null: false, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create index(:posts, ["body gin_trgm_ops"], name: "posts_body_gin_index", using: "GIN")

    create index(:posts, ["title gin_trgm_ops"], name: "posts_title_gin_index", using: "GIN")

    create table(:post_translations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "post_translations_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "post_translations_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :target_locale, :text, null: false
      add :title, :text, null: false
      add :body, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:post_translations, [:post_id, :target_locale],
             name: "post_translations_unique_post_target_locale_index"
           )

    create table(:acknowledgements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "acknowledgements_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :post_id,
          references(:posts,
            column: :id,
            name: "acknowledgements_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "acknowledgements_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:acknowledgements, [:post_id, :user_id],
             name: "acknowledgements_unique_post_user_index"
           )

    create constraint(:shoutouts, :no_self_shoutout,
             check: """
               sender_id <> recipient_id
             """
           )
  end

  def down do
    drop_if_exists constraint(:shoutouts, :no_self_shoutout)

    drop constraint(:acknowledgements, "acknowledgements_organization_id_fkey")

    drop constraint(:acknowledgements, "acknowledgements_post_id_fkey")

    drop constraint(:acknowledgements, "acknowledgements_user_id_fkey")

    drop_if_exists unique_index(:acknowledgements, [:post_id, :user_id],
                     name: "acknowledgements_unique_post_user_index"
                   )

    drop table(:acknowledgements)

    drop constraint(:post_translations, "post_translations_organization_id_fkey")

    drop constraint(:post_translations, "post_translations_post_id_fkey")

    drop_if_exists unique_index(:post_translations, [:post_id, :target_locale],
                     name: "post_translations_unique_post_target_locale_index"
                   )

    drop table(:post_translations)

    drop constraint(:posts, "posts_organization_id_fkey")

    drop constraint(:posts, "posts_venue_id_fkey")

    drop constraint(:posts, "posts_author_id_fkey")

    drop_if_exists index(:posts, ["title gin_trgm_ops"], name: "posts_title_gin_index")

    drop_if_exists index(:posts, ["body gin_trgm_ops"], name: "posts_body_gin_index")

    drop table(:posts)

    drop constraint(:shoutouts, "shoutouts_organization_id_fkey")

    drop constraint(:shoutouts, "shoutouts_sender_id_fkey")

    drop constraint(:shoutouts, "shoutouts_recipient_id_fkey")

    drop_if_exists index(:shoutouts, ["body gin_trgm_ops"], name: "shoutouts_body_gin_index")

    drop table(:shoutouts)
  end
end
