defmodule CrewPoc.Repo.Migrations.AddConversationVenueOrShiftConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:conversations, :venue_or_shift_present,
             check: """
               venue_id IS NOT NULL OR shift_id IS NOT NULL
             """
           )
  end

  def down do
    drop_if_exists constraint(:conversations, :venue_or_shift_present)
  end
end
