defmodule CrewPoc.Repo.Migrations.CascadeMembershipsFromVenuesAndUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:venue_memberships, "venue_memberships_user_id_fkey")

    drop constraint(:venue_memberships, "venue_memberships_venue_id_fkey")

    alter table(:venue_memberships) do
      modify :venue_id,
             references(:venues,
               column: :id,
               name: "venue_memberships_venue_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "venue_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    drop constraint(:conversation_memberships, "conversation_memberships_user_id_fkey")

    alter table(:conversation_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "conversation_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:conversation_memberships, "conversation_memberships_user_id_fkey")

    alter table(:conversation_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "conversation_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:venue_memberships, "venue_memberships_venue_id_fkey")

    drop constraint(:venue_memberships, "venue_memberships_user_id_fkey")

    alter table(:venue_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "venue_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :venue_id,
             references(:venues,
               column: :id,
               name: "venue_memberships_venue_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
