defmodule CrewPoc.Repo.Migrations.AddAccountsAndVenuesDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:venues, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :city, :text, null: false
      add :timezone, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false
    end

    create unique_index(:venues, [:organization_id, :slug],
             name: "venues_unique_slug_per_org_index"
           )

    create table(:venue_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false

      add :venue_id,
          references(:venues,
            column: :id,
            name: "venue_memberships_venue_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:venue_memberships, [:user_id, :venue_id],
             name: "venue_memberships_unique_user_venue_index"
           )

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:venue_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "venue_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :email, :text, null: false
      add :name, :text, null: false
      add :organization_id, :uuid, null: false
      add :role, :text, null: false, default: "staff"
      add :locale, :text, null: false, default: "en"
      add :job_title, :text, null: false
      add :birthday, :date, null: false
      add :started_at, :date, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:venues) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "venues_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "users_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    drop_if_exists unique_index(:organizations, [:name], name: "organizations_unique_name_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :slug
      remove :name
    end

    drop constraint(:users, "users_organization_id_fkey")

    alter table(:users) do
      modify :organization_id, :uuid
    end

    drop constraint(:venues, "venues_organization_id_fkey")

    alter table(:venues) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :started_at
      remove :birthday
      remove :job_title
      remove :locale
      remove :role
      remove :organization_id
      remove :name
      remove :email
    end

    drop constraint(:venue_memberships, "venue_memberships_user_id_fkey")

    alter table(:venue_memberships) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop constraint(:venue_memberships, "venue_memberships_venue_id_fkey")

    drop_if_exists unique_index(:venue_memberships, [:user_id, :venue_id],
                     name: "venue_memberships_unique_user_venue_index"
                   )

    drop table(:venue_memberships)

    drop_if_exists unique_index(:venues, [:organization_id, :slug],
                     name: "venues_unique_slug_per_org_index"
                   )

    drop table(:venues)
  end
end
